name: Build and Publish

on:
  workflow_dispatch:
    inputs:
      BUILD_PATTERN:
        description: "Projects to build. Project will be build if project name is in build pattern."
        required: false
      UPLOAD_PATTERN:
        description: "Projects to upload. Project will be uploaded if project name is in upload pattern."
        required: false

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      #------------------------------
      - name: Checkout repository
        uses: actions/checkout@v2
      #------------------------------
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.300
      #-------------------------------
      - name: Build and Publish
        env:
          UPLOAD_NUGET: ${{ secrets.UPLOAD_NUGET }}
          UPLOAD_NUGET_API_KEY: ${{ secrets.UPLOAD_NUGET_API_KEY }}
          BUILD_PATTERN: ${{ inputs.BUILD_PATTERN }}
          UPLOAD_PATTERN: ${{ inputs.UPLOAD_PATTERN }}
        run: |
          chmod a+x ./build.sh
          ./build.sh --target Travis --ForceUploadPackages=true --RunCodeCoverage=false
      #-------------------------------
